// src/app/services/job.service.ts
import { Injectable, signal } from '@angular/core';
import { Job } from '../models/job.model';

@Injectable({ providedIn: 'root' })
export class JobService {
  private jobsSignal = signal<Job[]>([
    {
      id: 1,
      farmerId: 1,
      farmerName: 'Ramesh Patil',
      acres: 4,
      ratePerAcre: 800,
      amount: 3200,
      date: '2026-06-12',
      status: 'Paid',
    },
    {
      id: 2,
      farmerId: 2,
      farmerName: 'Suresh More',
      acres: 2.5,
      ratePerAcre: 800,
      amount: 2000,
      date: '2026-06-10',
      status: 'Pending',
    },
    {
      id: 3,
      farmerId: 3,
      farmerName: 'Anita Jadhav',
      acres: 3,
      ratePerAcre: 800,
      amount: 2400,
      date: '2026-06-08',
      status: 'Paid',
    },
    {
      id: 4,
      farmerId: 4,
      farmerName: 'Vikas Shinde',
      acres: 5,
      ratePerAcre: 800,
      amount: 4000,
      date: '2026-06-05',
      status: 'Pending',
    },
    {
      id: 5,
      farmerId: 5,
      farmerName: 'Sunita Kadam',
      acres: 2,
      ratePerAcre: 800,
      amount: 1600,
      date: '2026-06-04',
      status: 'Paid',
    },
    {
      id: 6,
      farmerId: 6,
      farmerName: 'Rahul Deshmukh',
      acres: 6,
      ratePerAcre: 800,
      amount: 4800,
      date: '2026-06-03',
      status: 'Paid',
    },
    {
      id: 7,
      farmerId: 7,
      farmerName: 'Pooja Mane',
      acres: 3.5,
      ratePerAcre: 800,
      amount: 2800,
      date: '2026-06-02',
      status: 'Pending',
    },
    {
      id: 8,
      farmerId: 8,
      farmerName: 'Amit Bhosale',
      acres: 4,
      ratePerAcre: 800,
      amount: 3200,
      date: '2026-06-01',
      status: 'Paid',
    },
    {
      id: 9,
      farmerId: 9,
      farmerName: 'Vijay Sawant',
      acres: 2,
      ratePerAcre: 800,
      amount: 1600,
      date: '2026-05-28',
      status: 'Paid',
    },
    {
      id: 10,
      farmerId: 10,
      farmerName: 'Deepali Pawar',
      acres: 5,
      ratePerAcre: 800,
      amount: 4000,
      date: '2026-05-25',
      status: 'Pending',
    },
    {
      id: 11,
      farmerId: 11,
      farmerName: 'Sanjay Nikam',
      acres: 3,
      ratePerAcre: 800,
      amount: 2400,
      date: '2026-05-20',
      status: 'Paid',
    },
    {
      id: 12,
      farmerId: 12,
      farmerName: 'Rekha Gaikwad',
      acres: 4.5,
      ratePerAcre: 800,
      amount: 3600,
      date: '2026-05-18',
      status: 'Pending',
    },
    {
      id: 13,
      farmerId: 13,
      farmerName: 'Mahesh Thorat',
      acres: 2,
      ratePerAcre: 800,
      amount: 1600,
      date: '2026-05-15',
      status: 'Paid',
    },
    {
      id: 14,
      farmerId: 14,
      farmerName: 'Kavita Salunkhe',
      acres: 7,
      ratePerAcre: 800,
      amount: 5600,
      date: '2026-05-12',
      status: 'Pending',
    },
    {
      id: 15,
      farmerId: 15,
      farmerName: 'Prasad Jagtap',
      acres: 3,
      ratePerAcre: 800,
      amount: 2400,
      date: '2026-05-10',
      status: 'Paid',
    },
    {
      id: 16,
      farmerId: 16,
      farmerName: 'Seema Londhe',
      acres: 4,
      ratePerAcre: 800,
      amount: 3200,
      date: '2026-05-08',
      status: 'Paid',
    },
    {
      id: 17,
      farmerId: 17,
      farmerName: 'Vishal Gawade',
      acres: 2.5,
      ratePerAcre: 800,
      amount: 2000,
      date: '2026-05-05',
      status: 'Pending',
    },
    {
      id: 18,
      farmerId: 18,
      farmerName: 'Archana Kokare',
      acres: 3,
      ratePerAcre: 800,
      amount: 2400,
      date: '2026-05-02',
      status: 'Paid',
    },
    {
      id: 19,
      farmerId: 19,
      farmerName: 'Nitin Waghmare',
      acres: 6,
      ratePerAcre: 800,
      amount: 4800,
      date: '2026-04-28',
      status: 'Paid',
    },
    {
      id: 20,
      farmerId: 20,
      farmerName: 'Jyoti Dhumal',
      acres: 4,
      ratePerAcre: 800,
      amount: 3200,
      date: '2026-04-25',
      status: 'Pending',
    },
    {
      id: 21,
      farmerId: 21,
      farmerName: 'Sandip Kumbhar',
      acres: 5,
      ratePerAcre: 800,
      amount: 4000,
      date: '2026-04-22',
      status: 'Paid',
    },
    {
      id: 22,
      farmerId: 22,
      farmerName: 'Manisha Chavan',
      acres: 2,
      ratePerAcre: 800,
      amount: 1600,
      date: '2026-04-20',
      status: 'Paid',
    },
    {
      id: 23,
      farmerId: 23,
      farmerName: 'Ajay Shinde',
      acres: 3.5,
      ratePerAcre: 800,
      amount: 2800,
      date: '2026-04-18',
      status: 'Pending',
    },
    {
      id: 24,
      farmerId: 24,
      farmerName: 'Usha Mohite',
      acres: 4,
      ratePerAcre: 800,
      amount: 3200,
      date: '2026-04-15',
      status: 'Pending',
    },
    {
      id: 25,
      farmerId: 25,
      farmerName: 'Rohan Deshpande',
      acres: 2,
      ratePerAcre: 800,
      amount: 1600,
      date: '2026-04-12',
      status: 'Paid',
    },
    {
      id: 26,
      farmerId: 26,
      farmerName: 'Megha Kulkarni',
      acres: 3,
      ratePerAcre: 800,
      amount: 2400,
      date: '2026-04-10',
      status: 'Paid',
    },
    {
      id: 27,
      farmerId: 27,
      farmerName: 'Tushar Raut',
      acres: 4,
      ratePerAcre: 800,
      amount: 3200,
      date: '2026-04-08',
      status: 'Pending',
    },
    {
      id: 28,
      farmerId: 28,
      farmerName: 'Varsha Mali',
      acres: 6,
      ratePerAcre: 800,
      amount: 4800,
      date: '2026-04-05',
      status: 'Pending',
    },
    {
      id: 29,
      farmerId: 29,
      farmerName: 'Swapnil Sonawane',
      acres: 3,
      ratePerAcre: 800,
      amount: 2400,
      date: '2026-04-02',
      status: 'Paid',
    },
    {
      id: 30,
      farmerId: 30,
      farmerName: 'Shital Ingale',
      acres: 2.5,
      ratePerAcre: 800,
      amount: 2000,
      date: '2026-03-28',
      status: 'Pending',
    },
    {
      id: 31,
      farmerId: 31,
      farmerName: 'Pravin Kale',
      acres: 5,
      ratePerAcre: 800,
      amount: 4000,
      date: '2026-03-25',
      status: 'Paid',
    },
    {
      id: 32,
      farmerId: 32,
      farmerName: 'Snehal Ghodake',
      acres: 3,
      ratePerAcre: 800,
      amount: 2400,
      date: '2026-03-22',
      status: 'Paid',
    },
    {
      id: 33,
      farmerId: 33,
      farmerName: 'Sameer Bhagat',
      acres: 4,
      ratePerAcre: 800,
      amount: 3200,
      date: '2026-03-20',
      status: 'Pending',
    },
    {
      id: 34,
      farmerId: 34,
      farmerName: 'Rupali Patil',
      acres: 7,
      ratePerAcre: 800,
      amount: 5600,
      date: '2026-03-18',
      status: 'Paid',
    },
    {
      id: 35,
      farmerId: 35,
      farmerName: 'Ganesh Zende',
      acres: 2,
      ratePerAcre: 800,
      amount: 1600,
      date: '2026-03-15',
      status: 'Pending',
    },
    {
      id: 36,
      farmerId: 36,
      farmerName: 'Vidya Deshmukh',
      acres: 3.5,
      ratePerAcre: 800,
      amount: 2800,
      date: '2026-03-12',
      status: 'Paid',
    },
    {
      id: 37,
      farmerId: 37,
      farmerName: 'Abhijit Sutar',
      acres: 4,
      ratePerAcre: 800,
      amount: 3200,
      date: '2026-03-10',
      status: 'Pending',
    },
    {
      id: 38,
      farmerId: 38,
      farmerName: 'Ashwini Birajdar',
      acres: 6,
      ratePerAcre: 800,
      amount: 4800,
      date: '2026-03-08',
      status: 'Paid',
    },
    {
      id: 39,
      farmerId: 39,
      farmerName: 'Kiran Mane',
      acres: 3,
      ratePerAcre: 800,
      amount: 2400,
      date: '2026-03-05',
      status: 'Pending',
    },
    {
      id: 40,
      farmerId: 40,
      farmerName: 'Pallavi More',
      acres: 2,
      ratePerAcre: 800,
      amount: 1600,
      date: '2026-03-02',
      status: 'Paid',
    },
    {
      id: 41,
      farmerId: 41,
      farmerName: 'Dinesh Sawant',
      acres: 5,
      ratePerAcre: 800,
      amount: 4000,
      date: '2026-02-28',
      status: 'Pending',
    },
    {
      id: 42,
      farmerId: 42,
      farmerName: 'Smita Kamble',
      acres: 3,
      ratePerAcre: 800,
      amount: 2400,
      date: '2026-02-25',
      status: 'Paid',
    },
    {
      id: 43,
      farmerId: 43,
      farmerName: 'Hemant Kadam',
      acres: 4,
      ratePerAcre: 800,
      amount: 3200,
      date: '2026-02-22',
      status: 'Pending',
    },
    {
      id: 44,
      farmerId: 44,
      farmerName: 'Nilima Shewale',
      acres: 8,
      ratePerAcre: 800,
      amount: 6400,
      date: '2026-02-20',
      status: 'Pending',
    },
    {
      id: 45,
      farmerId: 45,
      farmerName: 'Sachin Ghatge',
      acres: 3,
      ratePerAcre: 800,
      amount: 2400,
      date: '2026-02-18',
      status: 'Paid',
    },
    {
      id: 46,
      farmerId: 46,
      farmerName: 'Tejaswini Nimbalkar',
      acres: 4,
      ratePerAcre: 800,
      amount: 3200,
      date: '2026-02-15',
      status: 'Pending',
    },
    {
      id: 47,
      farmerId: 47,
      farmerName: 'Manoj Salunkhe',
      acres: 2,
      ratePerAcre: 800,
      amount: 1600,
      date: '2026-02-12',
      status: 'Paid',
    },
    {
      id: 48,
      farmerId: 48,
      farmerName: 'Anjali Pawar',
      acres: 5,
      ratePerAcre: 800,
      amount: 4000,
      date: '2026-02-10',
      status: 'Pending',
    },
    {
      id: 49,
      farmerId: 49,
      farmerName: 'Yogesh Koli',
      acres: 3.5,
      ratePerAcre: 800,
      amount: 2800,
      date: '2026-02-08',
      status: 'Paid',
    },
    {
      id: 50,
      farmerId: 50,
      farmerName: 'Madhavi Suryawanshi',
      acres: 4,
      ratePerAcre: 800,
      amount: 3200,
      date: '2026-02-05',
      status: 'Pending',
    },
    {
      id: 51,
      farmerId: 28,
      farmerName: 'Varsha Mali',
      acres: 6,
      ratePerAcre: 800,
      amount: 5000,
      date: '2026-06-05',
      status: 'Pending',
    },
  ]);

  jobs = this.jobsSignal.asReadonly();

  getAll(): Job[] {
    return this.jobsSignal();
  }

  getById(id: number): Job | undefined {
    return this.jobsSignal().find((j) => j.id === id);
  }

  add(job: Omit<Job, 'id' | 'amount'>): void {
    const amount = job.acres * job.ratePerAcre;
    const newJob: Job = { ...job, id: Date.now(), amount };
    this.jobsSignal.update((jobs) => [newJob, ...jobs]);
  }

  update(id: number, changes: Partial<Job>): void {
    this.jobsSignal.update((jobs) =>
      jobs.map((j) => {
        if (j.id !== id) return j;
        const updated = { ...j, ...changes };
        updated.amount = updated.acres * updated.ratePerAcre;
        return updated;
      }),
    );
  }

  delete(id: number): void {
    this.jobsSignal.update((jobs) => jobs.filter((j) => j.id !== id));
  }

  markPaid(id: number): void {
    this.update(id, { status: 'Paid' });
  }

  getTotalEarned(): number {
    return this.jobsSignal().reduce((sum, j) => sum + j.amount, 0);
  }

  getPendingJobs(): Job[] {
    return this.jobsSignal().filter((j) => j.status === 'Pending');
  }

  getPendingAmount(): number {
    return this.getPendingJobs().reduce((sum, j) => sum + j.amount, 0);
  }
}
